version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: chore/update-dependencies
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
