import { useState } from "react";
import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { loadCharacters } from "../utils/loader/data-loader";
import { Character } from "../types/types";
import { CharacterSelect } from "../components/character-select";

interface AppProps {
    characters: Character[];
}

const App: NextPage<AppProps> = ({ characters }: AppProps) => {
    const [character, setCharacter] = useState<Character>();

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}>
                <h1>Gloomhaven Character Planner</h1>
            </header>

            <main className={styles.main}>
                <CharacterSelect
                    characters={characters}
                    setCharacter={setCharacter}
                />

                {character ? (
                    <Image
                        src={character.matImageUrl}
                        alt="Character mat"
                        width={600}
                        height={400}
                    />
                ) : null}
            </main>
        </div>
    );
};

const getStaticProps: GetStaticProps = async () => {
    return { props: { characters: loadCharacters() } };
};

export { getStaticProps };
export default App;
